/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiAnalisarExameRouteImport } from './routes/api/analisar-exame'
import { Route as ApiAssistenteIaRouteImport } from './routes/api/assistente-ia'
import { Route as ApiAssistenteIaConversasRouteImport } from './routes/api/assistente-ia-conversas'
import { Route as ApiChatIaRouteImport } from './routes/api/chat-ia'
import { Route as ApiDailyRoomRouteImport } from './routes/api/daily-room'
import { Route as ApiDeepgramTokenRouteImport } from './routes/api/deepgram-token'
import { Route as ApiLmeIaRouteImport } from './routes/api/lme-ia'
import { Route as ApiMapaFamiliarIaRouteImport } from './routes/api/mapa-familiar-ia'
import { Route as ApiWhatsappConviteRouteImport } from './routes/api/whatsapp-convite'
import { Route as ApiWhatsappWebhookRouteImport } from './routes/api/whatsapp-webhook'
import { Route as FFormIdRouteImport } from './routes/f.$formId'
import { Route as TTermoIdRouteImport } from './routes/t.$termoId'
import { Route as ApiBaseConhecimentoAtalhosRouteImport } from './routes/api/base-conhecimento/atalhos'
import { Route as ApiBaseConhecimentoBasesRouteImport } from './routes/api/base-conhecimento/bases'
import { Route as ApiBaseConhecimentoGerarMetadadosRouteImport } from './routes/api/base-conhecimento/gerar-metadados'
import { Route as ApiBaseConhecimentoItensRouteImport } from './routes/api/base-conhecimento/itens'
import { Route as ApiBryCancelEnvelopeRouteImport } from './routes/api/bry/cancel-envelope'
import { Route as ApiBryCreateEnvelopeRouteImport } from './routes/api/bry/create-envelope'
import { Route as ApiBryDownloadDocumentRouteImport } from './routes/api/bry/download-document'
import { Route as ApiBryGetEnvelopeRouteImport } from './routes/api/bry/get-envelope'
import { Route as ApiCidBuscarRouteImport } from './routes/api/cid/buscar'
import { Route as ApiMedicamentosBuscarRouteImport } from './routes/api/medicamentos/buscar'
import { Route as ApiPacientesMigrarRouteImport } from './routes/api/pacientes/migrar'
import { Route as ApiProtocolosAvaliarExameRouteImport } from './routes/api/protocolos/avaliar-exame'
import { Route as ApiProtocolosGerarIaRouteImport } from './routes/api/protocolos/gerar-ia'
import { Route as ApiProtocolosSincronizarRouteImport } from './routes/api/protocolos/sincronizar'
import { Route as ApiQuestionariosGerarIaRouteImport } from './routes/api/questionarios/gerar-ia'
import { Route as ApiSignatureAuthenticateRouteImport } from './routes/api/signature/authenticate'
import { Route as ApiSignatureCredentialRouteImport } from './routes/api/signature/credential'
import { Route as ApiSignatureLocalCertificateRouteImport } from './routes/api/signature/local-certificate'
import { Route as ApiSignatureSignRouteImport } from './routes/api/signature/sign'
import { Route as ApiTermosGerarIaRouteImport } from './routes/api/termos/gerar-ia'
import { Route as ApiTussBuscarRouteImport } from './routes/api/tuss/buscar'
import { Route as ApiTussCriarRouteImport } from './routes/api/tuss/criar'
import { Route as ApiPublicExtensaoChatRouteImport } from './routes/api/public/extensao/chat'
import { Route as ApiPublicExtensaoDeepgramTokenRouteImport } from './routes/api/public/extensao/deepgram-token'
import { Route as ApiPublicFormulariosCodigoRouteImport } from './routes/api/public/formularios/codigo'
import { Route as ApiPublicFormulariosPublicoRouteImport } from './routes/api/public/formularios/publico'
import { Route as ApiPublicFormulariosResponderRouteImport } from './routes/api/public/formularios/responder'
import { Route as ApiPublicHooksSyncInteracoesRouteImport } from './routes/api/public/hooks/sync-interacoes'
import { Route as ApiPublicHooksSyncTussRouteImport } from './routes/api/public/hooks/sync-tuss'
import { Route as ApiPublicSignatureCallbackRouteImport } from './routes/api/public/signature/callback'
import { Route as ApiPublicTermosAssinarRouteImport } from './routes/api/public/termos/assinar'
import { Route as ApiPublicTermosCodigoRouteImport } from './routes/api/public/termos/codigo'
import { Route as ApiPublicTermosPublicoRouteImport } from './routes/api/public/termos/publico'
import { Route as ApiPublicWebhooksBryRouteImport } from './routes/api/public/webhooks/bry'
import { Route as ApiSignatureIntegraBryCallbackRouteImport } from './routes/api/signature/integra-bry/callback'
import { Route as ApiSignatureIntegraBryLinkRouteImport } from './routes/api/signature/integra-bry/link'
import { Route as ApiSignatureIntegraBrySignRouteImport } from './routes/api/signature/integra-bry/sign'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAnalisarExameRoute = ApiAnalisarExameRouteImport.update({
  id: '/api/analisar-exame',
  path: '/api/analisar-exame',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAssistenteIaRoute = ApiAssistenteIaRouteImport.update({
  id: '/api/assistente-ia',
  path: '/api/assistente-ia',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAssistenteIaConversasRoute =
  ApiAssistenteIaConversasRouteImport.update({
    id: '/api/assistente-ia-conversas',
    path: '/api/assistente-ia-conversas',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiChatIaRoute = ApiChatIaRouteImport.update({
  id: '/api/chat-ia',
  path: '/api/chat-ia',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDailyRoomRoute = ApiDailyRoomRouteImport.update({
  id: '/api/daily-room',
  path: '/api/daily-room',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDeepgramTokenRoute = ApiDeepgramTokenRouteImport.update({
  id: '/api/deepgram-token',
  path: '/api/deepgram-token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLmeIaRoute = ApiLmeIaRouteImport.update({
  id: '/api/lme-ia',
  path: '/api/lme-ia',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMapaFamiliarIaRoute = ApiMapaFamiliarIaRouteImport.update({
  id: '/api/mapa-familiar-ia',
  path: '/api/mapa-familiar-ia',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWhatsappConviteRoute = ApiWhatsappConviteRouteImport.update({
  id: '/api/whatsapp-convite',
  path: '/api/whatsapp-convite',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWhatsappWebhookRoute = ApiWhatsappWebhookRouteImport.update({
  id: '/api/whatsapp-webhook',
  path: '/api/whatsapp-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const FFormIdRoute = FFormIdRouteImport.update({
  id: '/f/$formId',
  path: '/f/$formId',
  getParentRoute: () => rootRouteImport,
} as any)
const TTermoIdRoute = TTermoIdRouteImport.update({
  id: '/t/$termoId',
  path: '/t/$termoId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBaseConhecimentoAtalhosRoute =
  ApiBaseConhecimentoAtalhosRouteImport.update({
    id: '/api/base-conhecimento/atalhos',
    path: '/api/base-conhecimento/atalhos',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiBaseConhecimentoBasesRoute =
  ApiBaseConhecimentoBasesRouteImport.update({
    id: '/api/base-conhecimento/bases',
    path: '/api/base-conhecimento/bases',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiBaseConhecimentoGerarMetadadosRoute =
  ApiBaseConhecimentoGerarMetadadosRouteImport.update({
    id: '/api/base-conhecimento/gerar-metadados',
    path: '/api/base-conhecimento/gerar-metadados',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiBaseConhecimentoItensRoute =
  ApiBaseConhecimentoItensRouteImport.update({
    id: '/api/base-conhecimento/itens',
    path: '/api/base-conhecimento/itens',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiBryCancelEnvelopeRoute = ApiBryCancelEnvelopeRouteImport.update({
  id: '/api/bry/cancel-envelope',
  path: '/api/bry/cancel-envelope',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBryCreateEnvelopeRoute = ApiBryCreateEnvelopeRouteImport.update({
  id: '/api/bry/create-envelope',
  path: '/api/bry/create-envelope',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBryDownloadDocumentRoute = ApiBryDownloadDocumentRouteImport.update({
  id: '/api/bry/download-document',
  path: '/api/bry/download-document',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBryGetEnvelopeRoute = ApiBryGetEnvelopeRouteImport.update({
  id: '/api/bry/get-envelope',
  path: '/api/bry/get-envelope',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCidBuscarRoute = ApiCidBuscarRouteImport.update({
  id: '/api/cid/buscar',
  path: '/api/cid/buscar',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMedicamentosBuscarRoute = ApiMedicamentosBuscarRouteImport.update({
  id: '/api/medicamentos/buscar',
  path: '/api/medicamentos/buscar',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPacientesMigrarRoute = ApiPacientesMigrarRouteImport.update({
  id: '/api/pacientes/migrar',
  path: '/api/pacientes/migrar',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProtocolosAvaliarExameRoute =
  ApiProtocolosAvaliarExameRouteImport.update({
    id: '/api/protocolos/avaliar-exame',
    path: '/api/protocolos/avaliar-exame',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiProtocolosGerarIaRoute = ApiProtocolosGerarIaRouteImport.update({
  id: '/api/protocolos/gerar-ia',
  path: '/api/protocolos/gerar-ia',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProtocolosSincronizarRoute =
  ApiProtocolosSincronizarRouteImport.update({
    id: '/api/protocolos/sincronizar',
    path: '/api/protocolos/sincronizar',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiQuestionariosGerarIaRoute = ApiQuestionariosGerarIaRouteImport.update({
  id: '/api/questionarios/gerar-ia',
  path: '/api/questionarios/gerar-ia',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSignatureAuthenticateRoute =
  ApiSignatureAuthenticateRouteImport.update({
    id: '/api/signature/authenticate',
    path: '/api/signature/authenticate',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiSignatureCredentialRoute = ApiSignatureCredentialRouteImport.update({
  id: '/api/signature/credential',
  path: '/api/signature/credential',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSignatureLocalCertificateRoute =
  ApiSignatureLocalCertificateRouteImport.update({
    id: '/api/signature/local-certificate',
    path: '/api/signature/local-certificate',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiSignatureSignRoute = ApiSignatureSignRouteImport.update({
  id: '/api/signature/sign',
  path: '/api/signature/sign',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTermosGerarIaRoute = ApiTermosGerarIaRouteImport.update({
  id: '/api/termos/gerar-ia',
  path: '/api/termos/gerar-ia',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTussBuscarRoute = ApiTussBuscarRouteImport.update({
  id: '/api/tuss/buscar',
  path: '/api/tuss/buscar',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTussCriarRoute = ApiTussCriarRouteImport.update({
  id: '/api/tuss/criar',
  path: '/api/tuss/criar',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicExtensaoChatRoute = ApiPublicExtensaoChatRouteImport.update({
  id: '/api/public/extensao/chat',
  path: '/api/public/extensao/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicExtensaoDeepgramTokenRoute =
  ApiPublicExtensaoDeepgramTokenRouteImport.update({
    id: '/api/public/extensao/deepgram-token',
    path: '/api/public/extensao/deepgram-token',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicFormulariosCodigoRoute =
  ApiPublicFormulariosCodigoRouteImport.update({
    id: '/api/public/formularios/codigo',
    path: '/api/public/formularios/codigo',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicFormulariosPublicoRoute =
  ApiPublicFormulariosPublicoRouteImport.update({
    id: '/api/public/formularios/publico',
    path: '/api/public/formularios/publico',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicFormulariosResponderRoute =
  ApiPublicFormulariosResponderRouteImport.update({
    id: '/api/public/formularios/responder',
    path: '/api/public/formularios/responder',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksSyncInteracoesRoute =
  ApiPublicHooksSyncInteracoesRouteImport.update({
    id: '/api/public/hooks/sync-interacoes',
    path: '/api/public/hooks/sync-interacoes',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksSyncTussRoute = ApiPublicHooksSyncTussRouteImport.update({
  id: '/api/public/hooks/sync-tuss',
  path: '/api/public/hooks/sync-tuss',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSignatureCallbackRoute =
  ApiPublicSignatureCallbackRouteImport.update({
    id: '/api/public/signature/callback',
    path: '/api/public/signature/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicTermosAssinarRoute = ApiPublicTermosAssinarRouteImport.update({
  id: '/api/public/termos/assinar',
  path: '/api/public/termos/assinar',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTermosCodigoRoute = ApiPublicTermosCodigoRouteImport.update({
  id: '/api/public/termos/codigo',
  path: '/api/public/termos/codigo',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTermosPublicoRoute = ApiPublicTermosPublicoRouteImport.update({
  id: '/api/public/termos/publico',
  path: '/api/public/termos/publico',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWebhooksBryRoute = ApiPublicWebhooksBryRouteImport.update({
  id: '/api/public/webhooks/bry',
  path: '/api/public/webhooks/bry',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSignatureIntegraBryCallbackRoute =
  ApiSignatureIntegraBryCallbackRouteImport.update({
    id: '/api/signature/integra-bry/callback',
    path: '/api/signature/integra-bry/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiSignatureIntegraBryLinkRoute =
  ApiSignatureIntegraBryLinkRouteImport.update({
    id: '/api/signature/integra-bry/link',
    path: '/api/signature/integra-bry/link',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiSignatureIntegraBrySignRoute =
  ApiSignatureIntegraBrySignRouteImport.update({
    id: '/api/signature/integra-bry/sign',
    path: '/api/signature/integra-bry/sign',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/analisar-exame': typeof ApiAnalisarExameRoute
  '/api/assistente-ia': typeof ApiAssistenteIaRoute
  '/api/assistente-ia-conversas': typeof ApiAssistenteIaConversasRoute
  '/api/chat-ia': typeof ApiChatIaRoute
  '/api/daily-room': typeof ApiDailyRoomRoute
  '/api/deepgram-token': typeof ApiDeepgramTokenRoute
  '/api/lme-ia': typeof ApiLmeIaRoute
  '/api/mapa-familiar-ia': typeof ApiMapaFamiliarIaRoute
  '/api/whatsapp-convite': typeof ApiWhatsappConviteRoute
  '/api/whatsapp-webhook': typeof ApiWhatsappWebhookRoute
  '/f/$formId': typeof FFormIdRoute
  '/t/$termoId': typeof TTermoIdRoute
  '/api/base-conhecimento/atalhos': typeof ApiBaseConhecimentoAtalhosRoute
  '/api/base-conhecimento/bases': typeof ApiBaseConhecimentoBasesRoute
  '/api/base-conhecimento/gerar-metadados': typeof ApiBaseConhecimentoGerarMetadadosRoute
  '/api/base-conhecimento/itens': typeof ApiBaseConhecimentoItensRoute
  '/api/bry/cancel-envelope': typeof ApiBryCancelEnvelopeRoute
  '/api/bry/create-envelope': typeof ApiBryCreateEnvelopeRoute
  '/api/bry/download-document': typeof ApiBryDownloadDocumentRoute
  '/api/bry/get-envelope': typeof ApiBryGetEnvelopeRoute
  '/api/cid/buscar': typeof ApiCidBuscarRoute
  '/api/medicamentos/buscar': typeof ApiMedicamentosBuscarRoute
  '/api/pacientes/migrar': typeof ApiPacientesMigrarRoute
  '/api/protocolos/avaliar-exame': typeof ApiProtocolosAvaliarExameRoute
  '/api/protocolos/gerar-ia': typeof ApiProtocolosGerarIaRoute
  '/api/protocolos/sincronizar': typeof ApiProtocolosSincronizarRoute
  '/api/questionarios/gerar-ia': typeof ApiQuestionariosGerarIaRoute
  '/api/signature/authenticate': typeof ApiSignatureAuthenticateRoute
  '/api/signature/credential': typeof ApiSignatureCredentialRoute
  '/api/signature/local-certificate': typeof ApiSignatureLocalCertificateRoute
  '/api/signature/sign': typeof ApiSignatureSignRoute
  '/api/termos/gerar-ia': typeof ApiTermosGerarIaRoute
  '/api/tuss/buscar': typeof ApiTussBuscarRoute
  '/api/tuss/criar': typeof ApiTussCriarRoute
  '/api/public/extensao/chat': typeof ApiPublicExtensaoChatRoute
  '/api/public/extensao/deepgram-token': typeof ApiPublicExtensaoDeepgramTokenRoute
  '/api/public/formularios/codigo': typeof ApiPublicFormulariosCodigoRoute
  '/api/public/formularios/publico': typeof ApiPublicFormulariosPublicoRoute
  '/api/public/formularios/responder': typeof ApiPublicFormulariosResponderRoute
  '/api/public/hooks/sync-interacoes': typeof ApiPublicHooksSyncInteracoesRoute
  '/api/public/hooks/sync-tuss': typeof ApiPublicHooksSyncTussRoute
  '/api/public/signature/callback': typeof ApiPublicSignatureCallbackRoute
  '/api/public/termos/assinar': typeof ApiPublicTermosAssinarRoute
  '/api/public/termos/codigo': typeof ApiPublicTermosCodigoRoute
  '/api/public/termos/publico': typeof ApiPublicTermosPublicoRoute
  '/api/public/webhooks/bry': typeof ApiPublicWebhooksBryRoute
  '/api/signature/integra-bry/callback': typeof ApiSignatureIntegraBryCallbackRoute
  '/api/signature/integra-bry/link': typeof ApiSignatureIntegraBryLinkRoute
  '/api/signature/integra-bry/sign': typeof ApiSignatureIntegraBrySignRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/analisar-exame': typeof ApiAnalisarExameRoute
  '/api/assistente-ia': typeof ApiAssistenteIaRoute
  '/api/assistente-ia-conversas': typeof ApiAssistenteIaConversasRoute
  '/api/chat-ia': typeof ApiChatIaRoute
  '/api/daily-room': typeof ApiDailyRoomRoute
  '/api/deepgram-token': typeof ApiDeepgramTokenRoute
  '/api/lme-ia': typeof ApiLmeIaRoute
  '/api/mapa-familiar-ia': typeof ApiMapaFamiliarIaRoute
  '/api/whatsapp-convite': typeof ApiWhatsappConviteRoute
  '/api/whatsapp-webhook': typeof ApiWhatsappWebhookRoute
  '/f/$formId': typeof FFormIdRoute
  '/t/$termoId': typeof TTermoIdRoute
  '/api/base-conhecimento/atalhos': typeof ApiBaseConhecimentoAtalhosRoute
  '/api/base-conhecimento/bases': typeof ApiBaseConhecimentoBasesRoute
  '/api/base-conhecimento/gerar-metadados': typeof ApiBaseConhecimentoGerarMetadadosRoute
  '/api/base-conhecimento/itens': typeof ApiBaseConhecimentoItensRoute
  '/api/bry/cancel-envelope': typeof ApiBryCancelEnvelopeRoute
  '/api/bry/create-envelope': typeof ApiBryCreateEnvelopeRoute
  '/api/bry/download-document': typeof ApiBryDownloadDocumentRoute
  '/api/bry/get-envelope': typeof ApiBryGetEnvelopeRoute
  '/api/cid/buscar': typeof ApiCidBuscarRoute
  '/api/medicamentos/buscar': typeof ApiMedicamentosBuscarRoute
  '/api/pacientes/migrar': typeof ApiPacientesMigrarRoute
  '/api/protocolos/avaliar-exame': typeof ApiProtocolosAvaliarExameRoute
  '/api/protocolos/gerar-ia': typeof ApiProtocolosGerarIaRoute
  '/api/protocolos/sincronizar': typeof ApiProtocolosSincronizarRoute
  '/api/questionarios/gerar-ia': typeof ApiQuestionariosGerarIaRoute
  '/api/signature/authenticate': typeof ApiSignatureAuthenticateRoute
  '/api/signature/credential': typeof ApiSignatureCredentialRoute
  '/api/signature/local-certificate': typeof ApiSignatureLocalCertificateRoute
  '/api/signature/sign': typeof ApiSignatureSignRoute
  '/api/termos/gerar-ia': typeof ApiTermosGerarIaRoute
  '/api/tuss/buscar': typeof ApiTussBuscarRoute
  '/api/tuss/criar': typeof ApiTussCriarRoute
  '/api/public/extensao/chat': typeof ApiPublicExtensaoChatRoute
  '/api/public/extensao/deepgram-token': typeof ApiPublicExtensaoDeepgramTokenRoute
  '/api/public/formularios/codigo': typeof ApiPublicFormulariosCodigoRoute
  '/api/public/formularios/publico': typeof ApiPublicFormulariosPublicoRoute
  '/api/public/formularios/responder': typeof ApiPublicFormulariosResponderRoute
  '/api/public/hooks/sync-interacoes': typeof ApiPublicHooksSyncInteracoesRoute
  '/api/public/hooks/sync-tuss': typeof ApiPublicHooksSyncTussRoute
  '/api/public/signature/callback': typeof ApiPublicSignatureCallbackRoute
  '/api/public/termos/assinar': typeof ApiPublicTermosAssinarRoute
  '/api/public/termos/codigo': typeof ApiPublicTermosCodigoRoute
  '/api/public/termos/publico': typeof ApiPublicTermosPublicoRoute
  '/api/public/webhooks/bry': typeof ApiPublicWebhooksBryRoute
  '/api/signature/integra-bry/callback': typeof ApiSignatureIntegraBryCallbackRoute
  '/api/signature/integra-bry/link': typeof ApiSignatureIntegraBryLinkRoute
  '/api/signature/integra-bry/sign': typeof ApiSignatureIntegraBrySignRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/analisar-exame': typeof ApiAnalisarExameRoute
  '/api/assistente-ia': typeof ApiAssistenteIaRoute
  '/api/assistente-ia-conversas': typeof ApiAssistenteIaConversasRoute
  '/api/chat-ia': typeof ApiChatIaRoute
  '/api/daily-room': typeof ApiDailyRoomRoute
  '/api/deepgram-token': typeof ApiDeepgramTokenRoute
  '/api/lme-ia': typeof ApiLmeIaRoute
  '/api/mapa-familiar-ia': typeof ApiMapaFamiliarIaRoute
  '/api/whatsapp-convite': typeof ApiWhatsappConviteRoute
  '/api/whatsapp-webhook': typeof ApiWhatsappWebhookRoute
  '/f/$formId': typeof FFormIdRoute
  '/t/$termoId': typeof TTermoIdRoute
  '/api/base-conhecimento/atalhos': typeof ApiBaseConhecimentoAtalhosRoute
  '/api/base-conhecimento/bases': typeof ApiBaseConhecimentoBasesRoute
  '/api/base-conhecimento/gerar-metadados': typeof ApiBaseConhecimentoGerarMetadadosRoute
  '/api/base-conhecimento/itens': typeof ApiBaseConhecimentoItensRoute
  '/api/bry/cancel-envelope': typeof ApiBryCancelEnvelopeRoute
  '/api/bry/create-envelope': typeof ApiBryCreateEnvelopeRoute
  '/api/bry/download-document': typeof ApiBryDownloadDocumentRoute
  '/api/bry/get-envelope': typeof ApiBryGetEnvelopeRoute
  '/api/cid/buscar': typeof ApiCidBuscarRoute
  '/api/medicamentos/buscar': typeof ApiMedicamentosBuscarRoute
  '/api/pacientes/migrar': typeof ApiPacientesMigrarRoute
  '/api/protocolos/avaliar-exame': typeof ApiProtocolosAvaliarExameRoute
  '/api/protocolos/gerar-ia': typeof ApiProtocolosGerarIaRoute
  '/api/protocolos/sincronizar': typeof ApiProtocolosSincronizarRoute
  '/api/questionarios/gerar-ia': typeof ApiQuestionariosGerarIaRoute
  '/api/signature/authenticate': typeof ApiSignatureAuthenticateRoute
  '/api/signature/credential': typeof ApiSignatureCredentialRoute
  '/api/signature/local-certificate': typeof ApiSignatureLocalCertificateRoute
  '/api/signature/sign': typeof ApiSignatureSignRoute
  '/api/termos/gerar-ia': typeof ApiTermosGerarIaRoute
  '/api/tuss/buscar': typeof ApiTussBuscarRoute
  '/api/tuss/criar': typeof ApiTussCriarRoute
  '/api/public/extensao/chat': typeof ApiPublicExtensaoChatRoute
  '/api/public/extensao/deepgram-token': typeof ApiPublicExtensaoDeepgramTokenRoute
  '/api/public/formularios/codigo': typeof ApiPublicFormulariosCodigoRoute
  '/api/public/formularios/publico': typeof ApiPublicFormulariosPublicoRoute
  '/api/public/formularios/responder': typeof ApiPublicFormulariosResponderRoute
  '/api/public/hooks/sync-interacoes': typeof ApiPublicHooksSyncInteracoesRoute
  '/api/public/hooks/sync-tuss': typeof ApiPublicHooksSyncTussRoute
  '/api/public/signature/callback': typeof ApiPublicSignatureCallbackRoute
  '/api/public/termos/assinar': typeof ApiPublicTermosAssinarRoute
  '/api/public/termos/codigo': typeof ApiPublicTermosCodigoRoute
  '/api/public/termos/publico': typeof ApiPublicTermosPublicoRoute
  '/api/public/webhooks/bry': typeof ApiPublicWebhooksBryRoute
  '/api/signature/integra-bry/callback': typeof ApiSignatureIntegraBryCallbackRoute
  '/api/signature/integra-bry/link': typeof ApiSignatureIntegraBryLinkRoute
  '/api/signature/integra-bry/sign': typeof ApiSignatureIntegraBrySignRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/analisar-exame'
    | '/api/assistente-ia'
    | '/api/assistente-ia-conversas'
    | '/api/chat-ia'
    | '/api/daily-room'
    | '/api/deepgram-token'
    | '/api/lme-ia'
    | '/api/mapa-familiar-ia'
    | '/api/whatsapp-convite'
    | '/api/whatsapp-webhook'
    | '/f/$formId'
    | '/t/$termoId'
    | '/api/base-conhecimento/atalhos'
    | '/api/base-conhecimento/bases'
    | '/api/base-conhecimento/gerar-metadados'
    | '/api/base-conhecimento/itens'
    | '/api/bry/cancel-envelope'
    | '/api/bry/create-envelope'
    | '/api/bry/download-document'
    | '/api/bry/get-envelope'
    | '/api/cid/buscar'
    | '/api/medicamentos/buscar'
    | '/api/pacientes/migrar'
    | '/api/protocolos/avaliar-exame'
    | '/api/protocolos/gerar-ia'
    | '/api/protocolos/sincronizar'
    | '/api/questionarios/gerar-ia'
    | '/api/signature/authenticate'
    | '/api/signature/credential'
    | '/api/signature/local-certificate'
    | '/api/signature/sign'
    | '/api/termos/gerar-ia'
    | '/api/tuss/buscar'
    | '/api/tuss/criar'
    | '/api/public/extensao/chat'
    | '/api/public/extensao/deepgram-token'
    | '/api/public/formularios/codigo'
    | '/api/public/formularios/publico'
    | '/api/public/formularios/responder'
    | '/api/public/hooks/sync-interacoes'
    | '/api/public/hooks/sync-tuss'
    | '/api/public/signature/callback'
    | '/api/public/termos/assinar'
    | '/api/public/termos/codigo'
    | '/api/public/termos/publico'
    | '/api/public/webhooks/bry'
    | '/api/signature/integra-bry/callback'
    | '/api/signature/integra-bry/link'
    | '/api/signature/integra-bry/sign'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/analisar-exame'
    | '/api/assistente-ia'
    | '/api/assistente-ia-conversas'
    | '/api/chat-ia'
    | '/api/daily-room'
    | '/api/deepgram-token'
    | '/api/lme-ia'
    | '/api/mapa-familiar-ia'
    | '/api/whatsapp-convite'
    | '/api/whatsapp-webhook'
    | '/f/$formId'
    | '/t/$termoId'
    | '/api/base-conhecimento/atalhos'
    | '/api/base-conhecimento/bases'
    | '/api/base-conhecimento/gerar-metadados'
    | '/api/base-conhecimento/itens'
    | '/api/bry/cancel-envelope'
    | '/api/bry/create-envelope'
    | '/api/bry/download-document'
    | '/api/bry/get-envelope'
    | '/api/cid/buscar'
    | '/api/medicamentos/buscar'
    | '/api/pacientes/migrar'
    | '/api/protocolos/avaliar-exame'
    | '/api/protocolos/gerar-ia'
    | '/api/protocolos/sincronizar'
    | '/api/questionarios/gerar-ia'
    | '/api/signature/authenticate'
    | '/api/signature/credential'
    | '/api/signature/local-certificate'
    | '/api/signature/sign'
    | '/api/termos/gerar-ia'
    | '/api/tuss/buscar'
    | '/api/tuss/criar'
    | '/api/public/extensao/chat'
    | '/api/public/extensao/deepgram-token'
    | '/api/public/formularios/codigo'
    | '/api/public/formularios/publico'
    | '/api/public/formularios/responder'
    | '/api/public/hooks/sync-interacoes'
    | '/api/public/hooks/sync-tuss'
    | '/api/public/signature/callback'
    | '/api/public/termos/assinar'
    | '/api/public/termos/codigo'
    | '/api/public/termos/publico'
    | '/api/public/webhooks/bry'
    | '/api/signature/integra-bry/callback'
    | '/api/signature/integra-bry/link'
    | '/api/signature/integra-bry/sign'
  id:
    | '__root__'
    | '/'
    | '/api/analisar-exame'
    | '/api/assistente-ia'
    | '/api/assistente-ia-conversas'
    | '/api/chat-ia'
    | '/api/daily-room'
    | '/api/deepgram-token'
    | '/api/lme-ia'
    | '/api/mapa-familiar-ia'
    | '/api/whatsapp-convite'
    | '/api/whatsapp-webhook'
    | '/f/$formId'
    | '/t/$termoId'
    | '/api/base-conhecimento/atalhos'
    | '/api/base-conhecimento/bases'
    | '/api/base-conhecimento/gerar-metadados'
    | '/api/base-conhecimento/itens'
    | '/api/bry/cancel-envelope'
    | '/api/bry/create-envelope'
    | '/api/bry/download-document'
    | '/api/bry/get-envelope'
    | '/api/cid/buscar'
    | '/api/medicamentos/buscar'
    | '/api/pacientes/migrar'
    | '/api/protocolos/avaliar-exame'
    | '/api/protocolos/gerar-ia'
    | '/api/protocolos/sincronizar'
    | '/api/questionarios/gerar-ia'
    | '/api/signature/authenticate'
    | '/api/signature/credential'
    | '/api/signature/local-certificate'
    | '/api/signature/sign'
    | '/api/termos/gerar-ia'
    | '/api/tuss/buscar'
    | '/api/tuss/criar'
    | '/api/public/extensao/chat'
    | '/api/public/extensao/deepgram-token'
    | '/api/public/formularios/codigo'
    | '/api/public/formularios/publico'
    | '/api/public/formularios/responder'
    | '/api/public/hooks/sync-interacoes'
    | '/api/public/hooks/sync-tuss'
    | '/api/public/signature/callback'
    | '/api/public/termos/assinar'
    | '/api/public/termos/codigo'
    | '/api/public/termos/publico'
    | '/api/public/webhooks/bry'
    | '/api/signature/integra-bry/callback'
    | '/api/signature/integra-bry/link'
    | '/api/signature/integra-bry/sign'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiAnalisarExameRoute: typeof ApiAnalisarExameRoute
  ApiAssistenteIaRoute: typeof ApiAssistenteIaRoute
  ApiAssistenteIaConversasRoute: typeof ApiAssistenteIaConversasRoute
  ApiChatIaRoute: typeof ApiChatIaRoute
  ApiDailyRoomRoute: typeof ApiDailyRoomRoute
  ApiDeepgramTokenRoute: typeof ApiDeepgramTokenRoute
  ApiLmeIaRoute: typeof ApiLmeIaRoute
  ApiMapaFamiliarIaRoute: typeof ApiMapaFamiliarIaRoute
  ApiWhatsappConviteRoute: typeof ApiWhatsappConviteRoute
  ApiWhatsappWebhookRoute: typeof ApiWhatsappWebhookRoute
  FFormIdRoute: typeof FFormIdRoute
  TTermoIdRoute: typeof TTermoIdRoute
  ApiBaseConhecimentoAtalhosRoute: typeof ApiBaseConhecimentoAtalhosRoute
  ApiBaseConhecimentoBasesRoute: typeof ApiBaseConhecimentoBasesRoute
  ApiBaseConhecimentoGerarMetadadosRoute: typeof ApiBaseConhecimentoGerarMetadadosRoute
  ApiBaseConhecimentoItensRoute: typeof ApiBaseConhecimentoItensRoute
  ApiBryCancelEnvelopeRoute: typeof ApiBryCancelEnvelopeRoute
  ApiBryCreateEnvelopeRoute: typeof ApiBryCreateEnvelopeRoute
  ApiBryDownloadDocumentRoute: typeof ApiBryDownloadDocumentRoute
  ApiBryGetEnvelopeRoute: typeof ApiBryGetEnvelopeRoute
  ApiCidBuscarRoute: typeof ApiCidBuscarRoute
  ApiMedicamentosBuscarRoute: typeof ApiMedicamentosBuscarRoute
  ApiPacientesMigrarRoute: typeof ApiPacientesMigrarRoute
  ApiProtocolosAvaliarExameRoute: typeof ApiProtocolosAvaliarExameRoute
  ApiProtocolosGerarIaRoute: typeof ApiProtocolosGerarIaRoute
  ApiProtocolosSincronizarRoute: typeof ApiProtocolosSincronizarRoute
  ApiQuestionariosGerarIaRoute: typeof ApiQuestionariosGerarIaRoute
  ApiSignatureAuthenticateRoute: typeof ApiSignatureAuthenticateRoute
  ApiSignatureCredentialRoute: typeof ApiSignatureCredentialRoute
  ApiSignatureLocalCertificateRoute: typeof ApiSignatureLocalCertificateRoute
  ApiSignatureSignRoute: typeof ApiSignatureSignRoute
  ApiTermosGerarIaRoute: typeof ApiTermosGerarIaRoute
  ApiTussBuscarRoute: typeof ApiTussBuscarRoute
  ApiTussCriarRoute: typeof ApiTussCriarRoute
  ApiPublicExtensaoChatRoute: typeof ApiPublicExtensaoChatRoute
  ApiPublicExtensaoDeepgramTokenRoute: typeof ApiPublicExtensaoDeepgramTokenRoute
  ApiPublicFormulariosCodigoRoute: typeof ApiPublicFormulariosCodigoRoute
  ApiPublicFormulariosPublicoRoute: typeof ApiPublicFormulariosPublicoRoute
  ApiPublicFormulariosResponderRoute: typeof ApiPublicFormulariosResponderRoute
  ApiPublicHooksSyncInteracoesRoute: typeof ApiPublicHooksSyncInteracoesRoute
  ApiPublicHooksSyncTussRoute: typeof ApiPublicHooksSyncTussRoute
  ApiPublicSignatureCallbackRoute: typeof ApiPublicSignatureCallbackRoute
  ApiPublicTermosAssinarRoute: typeof ApiPublicTermosAssinarRoute
  ApiPublicTermosCodigoRoute: typeof ApiPublicTermosCodigoRoute
  ApiPublicTermosPublicoRoute: typeof ApiPublicTermosPublicoRoute
  ApiPublicWebhooksBryRoute: typeof ApiPublicWebhooksBryRoute
  ApiSignatureIntegraBryCallbackRoute: typeof ApiSignatureIntegraBryCallbackRoute
  ApiSignatureIntegraBryLinkRoute: typeof ApiSignatureIntegraBryLinkRoute
  ApiSignatureIntegraBrySignRoute: typeof ApiSignatureIntegraBrySignRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/analisar-exame': {
      id: '/api/analisar-exame'
      path: '/api/analisar-exame'
      fullPath: '/api/analisar-exame'
      preLoaderRoute: typeof ApiAnalisarExameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/assistente-ia': {
      id: '/api/assistente-ia'
      path: '/api/assistente-ia'
      fullPath: '/api/assistente-ia'
      preLoaderRoute: typeof ApiAssistenteIaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/assistente-ia-conversas': {
      id: '/api/assistente-ia-conversas'
      path: '/api/assistente-ia-conversas'
      fullPath: '/api/assistente-ia-conversas'
      preLoaderRoute: typeof ApiAssistenteIaConversasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat-ia': {
      id: '/api/chat-ia'
      path: '/api/chat-ia'
      fullPath: '/api/chat-ia'
      preLoaderRoute: typeof ApiChatIaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/daily-room': {
      id: '/api/daily-room'
      path: '/api/daily-room'
      fullPath: '/api/daily-room'
      preLoaderRoute: typeof ApiDailyRoomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/deepgram-token': {
      id: '/api/deepgram-token'
      path: '/api/deepgram-token'
      fullPath: '/api/deepgram-token'
      preLoaderRoute: typeof ApiDeepgramTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/lme-ia': {
      id: '/api/lme-ia'
      path: '/api/lme-ia'
      fullPath: '/api/lme-ia'
      preLoaderRoute: typeof ApiLmeIaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mapa-familiar-ia': {
      id: '/api/mapa-familiar-ia'
      path: '/api/mapa-familiar-ia'
      fullPath: '/api/mapa-familiar-ia'
      preLoaderRoute: typeof ApiMapaFamiliarIaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/whatsapp-convite': {
      id: '/api/whatsapp-convite'
      path: '/api/whatsapp-convite'
      fullPath: '/api/whatsapp-convite'
      preLoaderRoute: typeof ApiWhatsappConviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/whatsapp-webhook': {
      id: '/api/whatsapp-webhook'
      path: '/api/whatsapp-webhook'
      fullPath: '/api/whatsapp-webhook'
      preLoaderRoute: typeof ApiWhatsappWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/f/$formId': {
      id: '/f/$formId'
      path: '/f/$formId'
      fullPath: '/f/$formId'
      preLoaderRoute: typeof FFormIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/t/$termoId': {
      id: '/t/$termoId'
      path: '/t/$termoId'
      fullPath: '/t/$termoId'
      preLoaderRoute: typeof TTermoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/base-conhecimento/atalhos': {
      id: '/api/base-conhecimento/atalhos'
      path: '/api/base-conhecimento/atalhos'
      fullPath: '/api/base-conhecimento/atalhos'
      preLoaderRoute: typeof ApiBaseConhecimentoAtalhosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/base-conhecimento/bases': {
      id: '/api/base-conhecimento/bases'
      path: '/api/base-conhecimento/bases'
      fullPath: '/api/base-conhecimento/bases'
      preLoaderRoute: typeof ApiBaseConhecimentoBasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/base-conhecimento/gerar-metadados': {
      id: '/api/base-conhecimento/gerar-metadados'
      path: '/api/base-conhecimento/gerar-metadados'
      fullPath: '/api/base-conhecimento/gerar-metadados'
      preLoaderRoute: typeof ApiBaseConhecimentoGerarMetadadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/base-conhecimento/itens': {
      id: '/api/base-conhecimento/itens'
      path: '/api/base-conhecimento/itens'
      fullPath: '/api/base-conhecimento/itens'
      preLoaderRoute: typeof ApiBaseConhecimentoItensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bry/cancel-envelope': {
      id: '/api/bry/cancel-envelope'
      path: '/api/bry/cancel-envelope'
      fullPath: '/api/bry/cancel-envelope'
      preLoaderRoute: typeof ApiBryCancelEnvelopeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bry/create-envelope': {
      id: '/api/bry/create-envelope'
      path: '/api/bry/create-envelope'
      fullPath: '/api/bry/create-envelope'
      preLoaderRoute: typeof ApiBryCreateEnvelopeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bry/download-document': {
      id: '/api/bry/download-document'
      path: '/api/bry/download-document'
      fullPath: '/api/bry/download-document'
      preLoaderRoute: typeof ApiBryDownloadDocumentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bry/get-envelope': {
      id: '/api/bry/get-envelope'
      path: '/api/bry/get-envelope'
      fullPath: '/api/bry/get-envelope'
      preLoaderRoute: typeof ApiBryGetEnvelopeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cid/buscar': {
      id: '/api/cid/buscar'
      path: '/api/cid/buscar'
      fullPath: '/api/cid/buscar'
      preLoaderRoute: typeof ApiCidBuscarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/medicamentos/buscar': {
      id: '/api/medicamentos/buscar'
      path: '/api/medicamentos/buscar'
      fullPath: '/api/medicamentos/buscar'
      preLoaderRoute: typeof ApiMedicamentosBuscarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pacientes/migrar': {
      id: '/api/pacientes/migrar'
      path: '/api/pacientes/migrar'
      fullPath: '/api/pacientes/migrar'
      preLoaderRoute: typeof ApiPacientesMigrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/protocolos/avaliar-exame': {
      id: '/api/protocolos/avaliar-exame'
      path: '/api/protocolos/avaliar-exame'
      fullPath: '/api/protocolos/avaliar-exame'
      preLoaderRoute: typeof ApiProtocolosAvaliarExameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/protocolos/gerar-ia': {
      id: '/api/protocolos/gerar-ia'
      path: '/api/protocolos/gerar-ia'
      fullPath: '/api/protocolos/gerar-ia'
      preLoaderRoute: typeof ApiProtocolosGerarIaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/protocolos/sincronizar': {
      id: '/api/protocolos/sincronizar'
      path: '/api/protocolos/sincronizar'
      fullPath: '/api/protocolos/sincronizar'
      preLoaderRoute: typeof ApiProtocolosSincronizarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/questionarios/gerar-ia': {
      id: '/api/questionarios/gerar-ia'
      path: '/api/questionarios/gerar-ia'
      fullPath: '/api/questionarios/gerar-ia'
      preLoaderRoute: typeof ApiQuestionariosGerarIaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/signature/authenticate': {
      id: '/api/signature/authenticate'
      path: '/api/signature/authenticate'
      fullPath: '/api/signature/authenticate'
      preLoaderRoute: typeof ApiSignatureAuthenticateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/signature/credential': {
      id: '/api/signature/credential'
      path: '/api/signature/credential'
      fullPath: '/api/signature/credential'
      preLoaderRoute: typeof ApiSignatureCredentialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/signature/local-certificate': {
      id: '/api/signature/local-certificate'
      path: '/api/signature/local-certificate'
      fullPath: '/api/signature/local-certificate'
      preLoaderRoute: typeof ApiSignatureLocalCertificateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/signature/sign': {
      id: '/api/signature/sign'
      path: '/api/signature/sign'
      fullPath: '/api/signature/sign'
      preLoaderRoute: typeof ApiSignatureSignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/termos/gerar-ia': {
      id: '/api/termos/gerar-ia'
      path: '/api/termos/gerar-ia'
      fullPath: '/api/termos/gerar-ia'
      preLoaderRoute: typeof ApiTermosGerarIaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tuss/buscar': {
      id: '/api/tuss/buscar'
      path: '/api/tuss/buscar'
      fullPath: '/api/tuss/buscar'
      preLoaderRoute: typeof ApiTussBuscarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tuss/criar': {
      id: '/api/tuss/criar'
      path: '/api/tuss/criar'
      fullPath: '/api/tuss/criar'
      preLoaderRoute: typeof ApiTussCriarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/extensao/chat': {
      id: '/api/public/extensao/chat'
      path: '/api/public/extensao/chat'
      fullPath: '/api/public/extensao/chat'
      preLoaderRoute: typeof ApiPublicExtensaoChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/extensao/deepgram-token': {
      id: '/api/public/extensao/deepgram-token'
      path: '/api/public/extensao/deepgram-token'
      fullPath: '/api/public/extensao/deepgram-token'
      preLoaderRoute: typeof ApiPublicExtensaoDeepgramTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/formularios/codigo': {
      id: '/api/public/formularios/codigo'
      path: '/api/public/formularios/codigo'
      fullPath: '/api/public/formularios/codigo'
      preLoaderRoute: typeof ApiPublicFormulariosCodigoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/formularios/publico': {
      id: '/api/public/formularios/publico'
      path: '/api/public/formularios/publico'
      fullPath: '/api/public/formularios/publico'
      preLoaderRoute: typeof ApiPublicFormulariosPublicoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/formularios/responder': {
      id: '/api/public/formularios/responder'
      path: '/api/public/formularios/responder'
      fullPath: '/api/public/formularios/responder'
      preLoaderRoute: typeof ApiPublicFormulariosResponderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/sync-interacoes': {
      id: '/api/public/hooks/sync-interacoes'
      path: '/api/public/hooks/sync-interacoes'
      fullPath: '/api/public/hooks/sync-interacoes'
      preLoaderRoute: typeof ApiPublicHooksSyncInteracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/sync-tuss': {
      id: '/api/public/hooks/sync-tuss'
      path: '/api/public/hooks/sync-tuss'
      fullPath: '/api/public/hooks/sync-tuss'
      preLoaderRoute: typeof ApiPublicHooksSyncTussRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/signature/callback': {
      id: '/api/public/signature/callback'
      path: '/api/public/signature/callback'
      fullPath: '/api/public/signature/callback'
      preLoaderRoute: typeof ApiPublicSignatureCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/termos/assinar': {
      id: '/api/public/termos/assinar'
      path: '/api/public/termos/assinar'
      fullPath: '/api/public/termos/assinar'
      preLoaderRoute: typeof ApiPublicTermosAssinarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/termos/codigo': {
      id: '/api/public/termos/codigo'
      path: '/api/public/termos/codigo'
      fullPath: '/api/public/termos/codigo'
      preLoaderRoute: typeof ApiPublicTermosCodigoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/termos/publico': {
      id: '/api/public/termos/publico'
      path: '/api/public/termos/publico'
      fullPath: '/api/public/termos/publico'
      preLoaderRoute: typeof ApiPublicTermosPublicoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/bry': {
      id: '/api/public/webhooks/bry'
      path: '/api/public/webhooks/bry'
      fullPath: '/api/public/webhooks/bry'
      preLoaderRoute: typeof ApiPublicWebhooksBryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/signature/integra-bry/callback': {
      id: '/api/signature/integra-bry/callback'
      path: '/api/signature/integra-bry/callback'
      fullPath: '/api/signature/integra-bry/callback'
      preLoaderRoute: typeof ApiSignatureIntegraBryCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/signature/integra-bry/link': {
      id: '/api/signature/integra-bry/link'
      path: '/api/signature/integra-bry/link'
      fullPath: '/api/signature/integra-bry/link'
      preLoaderRoute: typeof ApiSignatureIntegraBryLinkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/signature/integra-bry/sign': {
      id: '/api/signature/integra-bry/sign'
      path: '/api/signature/integra-bry/sign'
      fullPath: '/api/signature/integra-bry/sign'
      preLoaderRoute: typeof ApiSignatureIntegraBrySignRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiAnalisarExameRoute: ApiAnalisarExameRoute,
  ApiAssistenteIaRoute: ApiAssistenteIaRoute,
  ApiAssistenteIaConversasRoute: ApiAssistenteIaConversasRoute,
  ApiChatIaRoute: ApiChatIaRoute,
  ApiDailyRoomRoute: ApiDailyRoomRoute,
  ApiDeepgramTokenRoute: ApiDeepgramTokenRoute,
  ApiLmeIaRoute: ApiLmeIaRoute,
  ApiMapaFamiliarIaRoute: ApiMapaFamiliarIaRoute,
  ApiWhatsappConviteRoute: ApiWhatsappConviteRoute,
  ApiWhatsappWebhookRoute: ApiWhatsappWebhookRoute,
  FFormIdRoute: FFormIdRoute,
  TTermoIdRoute: TTermoIdRoute,
  ApiBaseConhecimentoAtalhosRoute: ApiBaseConhecimentoAtalhosRoute,
  ApiBaseConhecimentoBasesRoute: ApiBaseConhecimentoBasesRoute,
  ApiBaseConhecimentoGerarMetadadosRoute:
    ApiBaseConhecimentoGerarMetadadosRoute,
  ApiBaseConhecimentoItensRoute: ApiBaseConhecimentoItensRoute,
  ApiBryCancelEnvelopeRoute: ApiBryCancelEnvelopeRoute,
  ApiBryCreateEnvelopeRoute: ApiBryCreateEnvelopeRoute,
  ApiBryDownloadDocumentRoute: ApiBryDownloadDocumentRoute,
  ApiBryGetEnvelopeRoute: ApiBryGetEnvelopeRoute,
  ApiCidBuscarRoute: ApiCidBuscarRoute,
  ApiMedicamentosBuscarRoute: ApiMedicamentosBuscarRoute,
  ApiPacientesMigrarRoute: ApiPacientesMigrarRoute,
  ApiProtocolosAvaliarExameRoute: ApiProtocolosAvaliarExameRoute,
  ApiProtocolosGerarIaRoute: ApiProtocolosGerarIaRoute,
  ApiProtocolosSincronizarRoute: ApiProtocolosSincronizarRoute,
  ApiQuestionariosGerarIaRoute: ApiQuestionariosGerarIaRoute,
  ApiSignatureAuthenticateRoute: ApiSignatureAuthenticateRoute,
  ApiSignatureCredentialRoute: ApiSignatureCredentialRoute,
  ApiSignatureLocalCertificateRoute: ApiSignatureLocalCertificateRoute,
  ApiSignatureSignRoute: ApiSignatureSignRoute,
  ApiTermosGerarIaRoute: ApiTermosGerarIaRoute,
  ApiTussBuscarRoute: ApiTussBuscarRoute,
  ApiTussCriarRoute: ApiTussCriarRoute,
  ApiPublicExtensaoChatRoute: ApiPublicExtensaoChatRoute,
  ApiPublicExtensaoDeepgramTokenRoute: ApiPublicExtensaoDeepgramTokenRoute,
  ApiPublicFormulariosCodigoRoute: ApiPublicFormulariosCodigoRoute,
  ApiPublicFormulariosPublicoRoute: ApiPublicFormulariosPublicoRoute,
  ApiPublicFormulariosResponderRoute: ApiPublicFormulariosResponderRoute,
  ApiPublicHooksSyncInteracoesRoute: ApiPublicHooksSyncInteracoesRoute,
  ApiPublicHooksSyncTussRoute: ApiPublicHooksSyncTussRoute,
  ApiPublicSignatureCallbackRoute: ApiPublicSignatureCallbackRoute,
  ApiPublicTermosAssinarRoute: ApiPublicTermosAssinarRoute,
  ApiPublicTermosCodigoRoute: ApiPublicTermosCodigoRoute,
  ApiPublicTermosPublicoRoute: ApiPublicTermosPublicoRoute,
  ApiPublicWebhooksBryRoute: ApiPublicWebhooksBryRoute,
  ApiSignatureIntegraBryCallbackRoute: ApiSignatureIntegraBryCallbackRoute,
  ApiSignatureIntegraBryLinkRoute: ApiSignatureIntegraBryLinkRoute,
  ApiSignatureIntegraBrySignRoute: ApiSignatureIntegraBrySignRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
