/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiDeepgramTokenRouteImport } from './routes/api/deepgram-token'
import { Route as ApiDailyRoomRouteImport } from './routes/api/daily-room'
import { Route as ApiChatIaRouteImport } from './routes/api/chat-ia'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDeepgramTokenRoute = ApiDeepgramTokenRouteImport.update({
  id: '/api/deepgram-token',
  path: '/api/deepgram-token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDailyRoomRoute = ApiDailyRoomRouteImport.update({
  id: '/api/daily-room',
  path: '/api/daily-room',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatIaRoute = ApiChatIaRouteImport.update({
  id: '/api/chat-ia',
  path: '/api/chat-ia',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/chat-ia': typeof ApiChatIaRoute
  '/api/daily-room': typeof ApiDailyRoomRoute
  '/api/deepgram-token': typeof ApiDeepgramTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/chat-ia': typeof ApiChatIaRoute
  '/api/daily-room': typeof ApiDailyRoomRoute
  '/api/deepgram-token': typeof ApiDeepgramTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/chat-ia': typeof ApiChatIaRoute
  '/api/daily-room': typeof ApiDailyRoomRoute
  '/api/deepgram-token': typeof ApiDeepgramTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/chat-ia' | '/api/daily-room' | '/api/deepgram-token'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/chat-ia' | '/api/daily-room' | '/api/deepgram-token'
  id:
    | '__root__'
    | '/'
    | '/api/chat-ia'
    | '/api/daily-room'
    | '/api/deepgram-token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiChatIaRoute: typeof ApiChatIaRoute
  ApiDailyRoomRoute: typeof ApiDailyRoomRoute
  ApiDeepgramTokenRoute: typeof ApiDeepgramTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/deepgram-token': {
      id: '/api/deepgram-token'
      path: '/api/deepgram-token'
      fullPath: '/api/deepgram-token'
      preLoaderRoute: typeof ApiDeepgramTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/daily-room': {
      id: '/api/daily-room'
      path: '/api/daily-room'
      fullPath: '/api/daily-room'
      preLoaderRoute: typeof ApiDailyRoomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat-ia': {
      id: '/api/chat-ia'
      path: '/api/chat-ia'
      fullPath: '/api/chat-ia'
      preLoaderRoute: typeof ApiChatIaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiChatIaRoute: ApiChatIaRoute,
  ApiDailyRoomRoute: ApiDailyRoomRoute,
  ApiDeepgramTokenRoute: ApiDeepgramTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
