-- Migration: re-popula lista_portaria344/tipo_receita com matching por PALAVRA INTEIRA
-- (regex com fronteira de palavra), em vez de igualdade exata.
--
-- Motivo: no banco, muitas substâncias vêm no formato "SAL DE PRINCÍPIO ATIVO"
-- (ex: CLORIDRATO DE TRAMADOL, MALEATO DE INDACATEROL, HIDROGENOTARTARATO DE
-- RIVASTIGMINA). A função grupo_busca_substancia só remove o sal quando ele
-- vem DEPOIS do nome (sufixo), não quando vem antes com "DE" no meio. Por
-- isso a igualdade exata perdia a maioria dessas substâncias.
--
-- Esta migration casa quando o nome da substância da Portaria 344 aparece
-- como PALAVRA(S) INTEIRA(S) dentro de grupo_busca / nome_dcb / nome_exibicao,
-- usando fronteiras não-alfanuméricas dos dois lados — o que evita falsos
-- positivos como "OPIO" dentro de "PROPIONATO".
--
-- Quando mais de um nome da portaria bate na mesma substância, fica o mais
-- específico (nome mais longo).

WITH candidatos AS (
  SELECT
    s.id_substancia,
    v.lista,
    v.tipo_receita,
    length(v.nome) AS especificidade
  FROM public.substancias s
  JOIN (VALUES
  ('ACETILMETADOL', 'A1', 'Notificação de Receita A (amarela)'),
  ('ACETORFINA', 'A1', 'Notificação de Receita A (amarela)'),
  ('ALFACETILMETADOL', 'A1', 'Notificação de Receita A (amarela)'),
  ('ALFAMEPRODINA', 'A1', 'Notificação de Receita A (amarela)'),
  ('ALFAMETADOL', 'A1', 'Notificação de Receita A (amarela)'),
  ('ALFAPRODINA', 'A1', 'Notificação de Receita A (amarela)'),
  ('ALFENTANILA', 'A1', 'Notificação de Receita A (amarela)'),
  ('ALILPRODINA', 'A1', 'Notificação de Receita A (amarela)'),
  ('ANILERIDINA', 'A1', 'Notificação de Receita A (amarela)'),
  ('BENZETIDINA', 'A1', 'Notificação de Receita A (amarela)'),
  ('BENZILMORFINA', 'A1', 'Notificação de Receita A (amarela)'),
  ('BENZOILMORFINA', 'A1', 'Notificação de Receita A (amarela)'),
  ('BETACETILMETADOL', 'A1', 'Notificação de Receita A (amarela)'),
  ('BETAMEPRODINA', 'A1', 'Notificação de Receita A (amarela)'),
  ('BETAMETADOL', 'A1', 'Notificação de Receita A (amarela)'),
  ('BETAPRODINA', 'A1', 'Notificação de Receita A (amarela)'),
  ('BECITRAMIDA', 'A1', 'Notificação de Receita A (amarela)'),
  ('BUPRENORFINA', 'A1', 'Notificação de Receita A (amarela)'),
  ('BUTORFANOL', 'A1', 'Notificação de Receita A (amarela)'),
  ('CETOBEMIDONA', 'A1', 'Notificação de Receita A (amarela)'),
  ('CLONITAZENO', 'A1', 'Notificação de Receita A (amarela)'),
  ('CODOXIMA', 'A1', 'Notificação de Receita A (amarela)'),
  ('CONCENTRADO DE PALHA DE DORMIDEIRA', 'A1', 'Notificação de Receita A (amarela)'),
  ('DEXTROMORAMIDA', 'A1', 'Notificação de Receita A (amarela)'),
  ('DIAMPROMIDA', 'A1', 'Notificação de Receita A (amarela)'),
  ('DIETILTIAMBUTENO', 'A1', 'Notificação de Receita A (amarela)'),
  ('DIFENOXILATO', 'A1', 'Notificação de Receita A (amarela)'),
  ('DIFENOXINA', 'A1', 'Notificação de Receita A (amarela)'),
  ('DIIDROMORFINA', 'A1', 'Notificação de Receita A (amarela)'),
  ('DIMEFEPTANOL', 'A1', 'Notificação de Receita A (amarela)'),
  ('METADOL', 'A1', 'Notificação de Receita A (amarela)'),
  ('DIMENOXADOL', 'A1', 'Notificação de Receita A (amarela)'),
  ('DIMETILTIAMBUTENO', 'A1', 'Notificação de Receita A (amarela)'),
  ('DIOXAFETILA', 'A1', 'Notificação de Receita A (amarela)'),
  ('DIPIPANONA', 'A1', 'Notificação de Receita A (amarela)'),
  ('DROTEBANOL', 'A1', 'Notificação de Receita A (amarela)'),
  ('ETILMETILTIAMBUTENO', 'A1', 'Notificação de Receita A (amarela)'),
  ('ETONITAZENO', 'A1', 'Notificação de Receita A (amarela)'),
  ('ETORFINA', 'A1', 'Notificação de Receita A (amarela)'),
  ('ETOXERIDINA', 'A1', 'Notificação de Receita A (amarela)'),
  ('FENADOXONA', 'A1', 'Notificação de Receita A (amarela)'),
  ('FENAMPROMIDA', 'A1', 'Notificação de Receita A (amarela)'),
  ('FENAZOCINA', 'A1', 'Notificação de Receita A (amarela)'),
  ('FENOMORFANO', 'A1', 'Notificação de Receita A (amarela)'),
  ('FENOPERIDINA', 'A1', 'Notificação de Receita A (amarela)'),
  ('FENTANILA', 'A1', 'Notificação de Receita A (amarela)'),
  ('FURETIDINA', 'A1', 'Notificação de Receita A (amarela)'),
  ('HIDROCODONA', 'A1', 'Notificação de Receita A (amarela)'),
  ('HIDROMORFINOL', 'A1', 'Notificação de Receita A (amarela)'),
  ('HIDROMORFONA', 'A1', 'Notificação de Receita A (amarela)'),
  ('HIDROXIPETIDINA', 'A1', 'Notificação de Receita A (amarela)'),
  ('ISOMETADONA', 'A1', 'Notificação de Receita A (amarela)'),
  ('LEVOFENACILMORFANO', 'A1', 'Notificação de Receita A (amarela)'),
  ('LEVOMETORFANO', 'A1', 'Notificação de Receita A (amarela)'),
  ('LEVOMORAMIDA', 'A1', 'Notificação de Receita A (amarela)'),
  ('LEVORFANOL', 'A1', 'Notificação de Receita A (amarela)'),
  ('METADONA', 'A1', 'Notificação de Receita A (amarela)'),
  ('METAZOCINA', 'A1', 'Notificação de Receita A (amarela)'),
  ('METILDESORFINA', 'A1', 'Notificação de Receita A (amarela)'),
  ('METILDIIDROMORFINA', 'A1', 'Notificação de Receita A (amarela)'),
  ('METOPONA', 'A1', 'Notificação de Receita A (amarela)'),
  ('MIROFINA', 'A1', 'Notificação de Receita A (amarela)'),
  ('MORFERIDINA', 'A1', 'Notificação de Receita A (amarela)'),
  ('MORFINA', 'A1', 'Notificação de Receita A (amarela)'),
  ('MORINAMIDA', 'A1', 'Notificação de Receita A (amarela)'),
  ('NICOMORFINA', 'A1', 'Notificação de Receita A (amarela)'),
  ('NORACIMETADOL', 'A1', 'Notificação de Receita A (amarela)'),
  ('NORLEVORFANOL', 'A1', 'Notificação de Receita A (amarela)'),
  ('NORMETADONA', 'A1', 'Notificação de Receita A (amarela)'),
  ('NORMORFINA', 'A1', 'Notificação de Receita A (amarela)'),
  ('NORPIPANONA', 'A1', 'Notificação de Receita A (amarela)'),
  ('N-OXICODEINA', 'A1', 'Notificação de Receita A (amarela)'),
  ('OPIO', 'A1', 'Notificação de Receita A (amarela)'),
  ('OXICODONA', 'A1', 'Notificação de Receita A (amarela)'),
  ('N-OXIMORFINA', 'A1', 'Notificação de Receita A (amarela)'),
  ('PETIDINA', 'A1', 'Notificação de Receita A (amarela)'),
  ('PIMINODINA', 'A1', 'Notificação de Receita A (amarela)'),
  ('PIRITRAMIDA', 'A1', 'Notificação de Receita A (amarela)'),
  ('PROEPTAZINA', 'A1', 'Notificação de Receita A (amarela)'),
  ('PROPERIDINA', 'A1', 'Notificação de Receita A (amarela)'),
  ('RACEMETORFANO', 'A1', 'Notificação de Receita A (amarela)'),
  ('RACEMORAMIDA', 'A1', 'Notificação de Receita A (amarela)'),
  ('RACEMORFANO', 'A1', 'Notificação de Receita A (amarela)'),
  ('REMIFENTANILA', 'A1', 'Notificação de Receita A (amarela)'),
  ('SUFENTANILA', 'A1', 'Notificação de Receita A (amarela)'),
  ('TEBACONA', 'A1', 'Notificação de Receita A (amarela)'),
  ('ACETILDIIDROCODEINONA', 'A1', 'Notificação de Receita A (amarela)'),
  ('TEBAINA', 'A1', 'Notificação de Receita A (amarela)'),
  ('TILIDINA', 'A1', 'Notificação de Receita A (amarela)'),
  ('TRIMEPERIDINA', 'A1', 'Notificação de Receita A (amarela)'),
  ('ACETILDIIDROCODEINA', 'A2', 'Notificação de Receita A (amarela)'),
  ('CODEINA', 'A2', 'Notificação de Receita A (amarela)'),
  ('DEXTROPROPOXIFENO', 'A2', 'Notificação de Receita A (amarela)'),
  ('DIIDROCODEINA', 'A2', 'Notificação de Receita A (amarela)'),
  ('ETILMORFINA', 'A2', 'Notificação de Receita A (amarela)'),
  ('DIONINA', 'A2', 'Notificação de Receita A (amarela)'),
  ('FOLCODINA', 'A2', 'Notificação de Receita A (amarela)'),
  ('NALBUFINA', 'A2', 'Notificação de Receita A (amarela)'),
  ('NALORFINA', 'A2', 'Notificação de Receita A (amarela)'),
  ('NICOCODINA', 'A2', 'Notificação de Receita A (amarela)'),
  ('NICODICODINA', 'A2', 'Notificação de Receita A (amarela)'),
  ('NORCODEINA', 'A2', 'Notificação de Receita A (amarela)'),
  ('PROPIRAM', 'A2', 'Notificação de Receita A (amarela)'),
  ('TRAMADOL', 'A2', 'Notificação de Receita A (amarela)'),
  ('ANFETAMINA', 'A3', 'Notificação de Receita A (amarela)'),
  ('CATINA', 'A3', 'Notificação de Receita A (amarela)'),
  ('CLOBENZOREX', 'A3', 'Notificação de Receita A (amarela)'),
  ('CLORFENTERMINA', 'A3', 'Notificação de Receita A (amarela)'),
  ('DEXANFETAMINA', 'A3', 'Notificação de Receita A (amarela)'),
  ('FENCICLIDINA', 'A3', 'Notificação de Receita A (amarela)'),
  ('FENETILINA', 'A3', 'Notificação de Receita A (amarela)'),
  ('FENMETRAZINA', 'A3', 'Notificação de Receita A (amarela)'),
  ('LEVANFETAMINA', 'A3', 'Notificação de Receita A (amarela)'),
  ('LEVOMETANFETAMINA', 'A3', 'Notificação de Receita A (amarela)'),
  ('METANFETAMINA', 'A3', 'Notificação de Receita A (amarela)'),
  ('METILFENIDATO', 'A3', 'Notificação de Receita A (amarela)'),
  ('TANFETAMINA', 'A3', 'Notificação de Receita A (amarela)'),
  ('ALOBARBITAL', 'B1', 'Notificação de Receita B (azul)'),
  ('ALPRAZOLAM', 'B1', 'Notificação de Receita B (azul)'),
  ('AMOBARBITAL', 'B1', 'Notificação de Receita B (azul)'),
  ('APROBARBITAL', 'B1', 'Notificação de Receita B (azul)'),
  ('BARBEXACLONA', 'B1', 'Notificação de Receita B (azul)'),
  ('BARBITAL', 'B1', 'Notificação de Receita B (azul)'),
  ('BROMAZEPAM', 'B1', 'Notificação de Receita B (azul)'),
  ('BROTIZOLAM', 'B1', 'Notificação de Receita B (azul)'),
  ('BUTALBITAL', 'B1', 'Notificação de Receita B (azul)'),
  ('BUTOBARBITAL', 'B1', 'Notificação de Receita B (azul)'),
  ('CAMAZEPAM', 'B1', 'Notificação de Receita B (azul)'),
  ('CETAZOLAM', 'B1', 'Notificação de Receita B (azul)'),
  ('CICLOBARBITAL', 'B1', 'Notificação de Receita B (azul)'),
  ('CLOBAZAM', 'B1', 'Notificação de Receita B (azul)'),
  ('CLONAZEPAM', 'B1', 'Notificação de Receita B (azul)'),
  ('CLORAZEPAM', 'B1', 'Notificação de Receita B (azul)'),
  ('CLORAZEPATO', 'B1', 'Notificação de Receita B (azul)'),
  ('CLORDIAZEPOXIDO', 'B1', 'Notificação de Receita B (azul)'),
  ('CLOTIAZEPAM', 'B1', 'Notificação de Receita B (azul)'),
  ('CLOXAZOLAM', 'B1', 'Notificação de Receita B (azul)'),
  ('DELORAZEPAM', 'B1', 'Notificação de Receita B (azul)'),
  ('DIAZEPAM', 'B1', 'Notificação de Receita B (azul)'),
  ('ESTAZOLAM', 'B1', 'Notificação de Receita B (azul)'),
  ('ETCLORVINOL', 'B1', 'Notificação de Receita B (azul)'),
  ('ETINAMATO', 'B1', 'Notificação de Receita B (azul)'),
  ('FENDIMETRAZINA', 'B1', 'Notificação de Receita B (azul)'),
  ('FENOBARBITAL', 'B1', 'Notificação de Receita B (azul)'),
  ('FLUDIAZEPAM', 'B1', 'Notificação de Receita B (azul)'),
  ('FLUNITRAZEPAM', 'B1', 'Notificação de Receita B (azul)'),
  ('FLURAZEPAM', 'B1', 'Notificação de Receita B (azul)'),
  ('GLUTETIMIDA', 'B1', 'Notificação de Receita B (azul)'),
  ('HALAZEPAM', 'B1', 'Notificação de Receita B (azul)'),
  ('HALOXAZOLAM', 'B1', 'Notificação de Receita B (azul)'),
  ('LEFETAMINA', 'B1', 'Notificação de Receita B (azul)'),
  ('LOFLAZEPATO ETILA', 'B1', 'Notificação de Receita B (azul)'),
  ('LOPRAZOLAM', 'B1', 'Notificação de Receita B (azul)'),
  ('LORAZEPAM', 'B1', 'Notificação de Receita B (azul)'),
  ('LORMETAZEPAM', 'B1', 'Notificação de Receita B (azul)'),
  ('MEDAZEPAM', 'B1', 'Notificação de Receita B (azul)'),
  ('MEPROBAMATO', 'B1', 'Notificação de Receita B (azul)'),
  ('MESOCARBO', 'B1', 'Notificação de Receita B (azul)'),
  ('METIL FENOBARBITAL', 'B1', 'Notificação de Receita B (azul)'),
  ('PROMINAL', 'B1', 'Notificação de Receita B (azul)'),
  ('METIPRILONA', 'B1', 'Notificação de Receita B (azul)'),
  ('MIDAZOLAM', 'B1', 'Notificação de Receita B (azul)'),
  ('N-ETILANFETAMINA', 'B1', 'Notificação de Receita B (azul)'),
  ('NIMETAZEPAM', 'B1', 'Notificação de Receita B (azul)'),
  ('NITRAZEPAM', 'B1', 'Notificação de Receita B (azul)'),
  ('NORCANFANO', 'B1', 'Notificação de Receita B (azul)'),
  ('FENCANFAMINA', 'B1', 'Notificação de Receita B (azul)'),
  ('NORDAZEPAM', 'B1', 'Notificação de Receita B (azul)'),
  ('OXAZEPAM', 'B1', 'Notificação de Receita B (azul)'),
  ('OXAZOLAM', 'B1', 'Notificação de Receita B (azul)'),
  ('PEMOLINA', 'B1', 'Notificação de Receita B (azul)'),
  ('PENTAZONINA', 'B1', 'Notificação de Receita B (azul)'),
  ('PENTOBARBITAL', 'B1', 'Notificação de Receita B (azul)'),
  ('PINAZEPAM', 'B1', 'Notificação de Receita B (azul)'),
  ('PIPRADOL', 'B1', 'Notificação de Receita B (azul)'),
  ('PIROVARELONA', 'B1', 'Notificação de Receita B (azul)'),
  ('PRAZEPAM', 'B1', 'Notificação de Receita B (azul)'),
  ('PROLINTANO', 'B1', 'Notificação de Receita B (azul)'),
  ('PROPILEXEDRINA', 'B1', 'Notificação de Receita B (azul)'),
  ('SECBUTABARBITAL', 'B1', 'Notificação de Receita B (azul)'),
  ('SECOBARBITAL', 'B1', 'Notificação de Receita B (azul)'),
  ('TEMAZEPAM', 'B1', 'Notificação de Receita B (azul)'),
  ('TETRAZEPAM', 'B1', 'Notificação de Receita B (azul)'),
  ('TIAMILAL', 'B1', 'Notificação de Receita B (azul)'),
  ('TIOPENTAL', 'B1', 'Notificação de Receita B (azul)'),
  ('TRIAZOLAM', 'B1', 'Notificação de Receita B (azul)'),
  ('TRIEXIFENIDIL', 'B1', 'Notificação de Receita B (azul)'),
  ('VINILBITAL', 'B1', 'Notificação de Receita B (azul)'),
  ('ZOLPIDEM', 'B1', 'Notificação de Receita B (azul)'),
  ('ZOPICLONA', 'B1', 'Notificação de Receita B (azul)'),
  ('AMINOREX', 'B2', 'Notificação de Receita B (azul)'),
  ('ANFEPRAMONA', 'B2', 'Notificação de Receita B (azul)'),
  ('DIETILPROPIONA', 'B2', 'Notificação de Receita B (azul)'),
  ('FEMPROPOREX', 'B2', 'Notificação de Receita B (azul)'),
  ('FENDIMETRAZINA', 'B2', 'Notificação de Receita B (azul)'),
  ('FENTERMINA', 'B2', 'Notificação de Receita B (azul)'),
  ('MAZINDOL', 'B2', 'Notificação de Receita B (azul)'),
  ('MEFENOREX', 'B2', 'Notificação de Receita B (azul)'),
  ('ACEPROMAZINA', 'C1', 'Receita de Controle Especial (2 vias)'),
  ('ACIDO VALPROICO', 'C1', 'Receita de Controle Especial (2 vias)'),
  ('AMANTADINA', 'C1', 'Receita de Controle Especial (2 vias)'),
  ('AMINEPTINA', 'C1', 'Receita de Controle Especial (2 vias)'),
  ('AMISSULPRIDA', 'C1', 'Receita de Controle Especial (2 vias)'),
  ('AMITRIPTILINA', 'C1', 'Receita de Controle Especial (2 vias)'),
  ('AMOXAPINA', 'C1', 'Receita de Controle Especial (2 vias)'),
  ('AZACICLONOL', 'C1', 'Receita de Controle Especial (2 vias)'),
  ('BECLAMIDA', 'C1', 'Receita de Controle Especial (2 vias)'),
  ('BENACTIZINA', 'C1', 'Receita de Controle Especial (2 vias)'),
  ('BENFLUOREX', 'C1', 'Receita de Controle Especial (2 vias)'),
  ('BENZOCTAMINA', 'C1', 'Receita de Controle Especial (2 vias)'),
  ('BENZOQUINAMIDA', 'C1', 'Receita de Controle Especial (2 vias)'),
  ('BIPERIDENO', 'C1', 'Receita de Controle Especial (2 vias)'),
  ('BUSPIRONA', 'C1', 'Receita de Controle Especial (2 vias)'),
  ('BUTAPERAZINA', 'C1', 'Receita de Controle Especial (2 vias)'),
  ('BUTRIPTILINA', 'C1', 'Receita de Controle Especial (2 vias)'),
  ('CAPTODIAMINA', 'C1', 'Receita de Controle Especial (2 vias)'),
  ('CARBAMAZEPINA', 'C1', 'Receita de Controle Especial (2 vias)'),
  ('CAROXAZONA', 'C1', 'Receita de Controle Especial (2 vias)'),
  ('CETAMINA', 'C1', 'Receita de Controle Especial (2 vias)'),
  ('CICLARBAMATO', 'C1', 'Receita de Controle Especial (2 vias)'),
  ('CICLEXEDRINA', 'C1', 'Receita de Controle Especial (2 vias)'),
  ('CICLOPENTOLATO', 'C1', 'Receita de Controle Especial (2 vias)'),
  ('CITALOPRAM', 'C1', 'Receita de Controle Especial (2 vias)'),
  ('CLOMACRANO', 'C1', 'Receita de Controle Especial (2 vias)'),
  ('CLOMETIAZOL', 'C1', 'Receita de Controle Especial (2 vias)'),
  ('CLOMIPRAMINA', 'C1', 'Receita de Controle Especial (2 vias)'),
  ('CLOREXADOL', 'C1', 'Receita de Controle Especial (2 vias)'),
  ('CLORPROMAZINA', 'C1', 'Receita de Controle Especial (2 vias)'),
  ('CLORPROTIXENO', 'C1', 'Receita de Controle Especial (2 vias)'),
  ('CLOTIAPINA', 'C1', 'Receita de Controle Especial (2 vias)'),
  ('CLOZAPINA', 'C1', 'Receita de Controle Especial (2 vias)'),
  ('DEANOL', 'C1', 'Receita de Controle Especial (2 vias)'),
  ('DESFLURANO', 'C1', 'Receita de Controle Especial (2 vias)'),
  ('DESIPRAMINA', 'C1', 'Receita de Controle Especial (2 vias)'),
  ('DEXETIMIDA', 'C1', 'Receita de Controle Especial (2 vias)'),
  ('DEXFENFLURAMINA', 'C1', 'Receita de Controle Especial (2 vias)'),
  ('DEXTROMETORFANO', 'C1', 'Receita de Controle Especial (2 vias)'),
  ('DIBENZEPINA', 'C1', 'Receita de Controle Especial (2 vias)'),
  ('DIMETRACRINA', 'C1', 'Receita de Controle Especial (2 vias)'),
  ('DISOPIRAMIDA', 'C1', 'Receita de Controle Especial (2 vias)'),
  ('DISSULFIRAM', 'C1', 'Receita de Controle Especial (2 vias)'),
  ('DIVALPROATO DE SODIO', 'C1', 'Receita de Controle Especial (2 vias)'),
  ('DIXIRAZINA', 'C1', 'Receita de Controle Especial (2 vias)'),
  ('DOXEPINA', 'C1', 'Receita de Controle Especial (2 vias)'),
  ('DROPERIDOL', 'C1', 'Receita de Controle Especial (2 vias)'),
  ('EMILCAMATO', 'C1', 'Receita de Controle Especial (2 vias)'),
  ('ENFLURANO', 'C1', 'Receita de Controle Especial (2 vias)'),
  ('ETOMIDATO', 'C1', 'Receita de Controle Especial (2 vias)'),
  ('ETOSSUXIMIDA', 'C1', 'Receita de Controle Especial (2 vias)'),
  ('ECTILUREIA', 'C1', 'Receita de Controle Especial (2 vias)'),
  ('FACETOPERANO', 'C1', 'Receita de Controle Especial (2 vias)'),
  ('LEVOFACETOPERANO', 'C1', 'Receita de Controle Especial (2 vias)'),
  ('FENAGLICODOL', 'C1', 'Receita de Controle Especial (2 vias)'),
  ('FENELZINA', 'C1', 'Receita de Controle Especial (2 vias)'),
  ('FENFLURAMINA', 'C1', 'Receita de Controle Especial (2 vias)'),
  ('FENITOINA', 'C1', 'Receita de Controle Especial (2 vias)'),
  ('FENILPROPANOLAMINA', 'C1', 'Receita de Controle Especial (2 vias)'),
  ('FENIPRAZINA', 'C1', 'Receita de Controle Especial (2 vias)'),
  ('FEMPROBAMATO', 'C1', 'Receita de Controle Especial (2 vias)'),
  ('FLUFENAZINA', 'C1', 'Receita de Controle Especial (2 vias)'),
  ('FLUMAZENIL', 'C1', 'Receita de Controle Especial (2 vias)'),
  ('FLUOXETINA', 'C1', 'Receita de Controle Especial (2 vias)'),
  ('FLUPENTIXOL', 'C1', 'Receita de Controle Especial (2 vias)'),
  ('FLUVOXAMINA', 'C1', 'Receita de Controle Especial (2 vias)'),
  ('HALOPERIDOL', 'C1', 'Receita de Controle Especial (2 vias)'),
  ('HALOTANO', 'C1', 'Receita de Controle Especial (2 vias)'),
  ('HIDRATO DE CLORAL', 'C1', 'Receita de Controle Especial (2 vias)'),
  ('HIDROCLORBEZETILAMINA', 'C1', 'Receita de Controle Especial (2 vias)'),
  ('HIDROXIDIONA', 'C1', 'Receita de Controle Especial (2 vias)'),
  ('HOMOFENAZINA', 'C1', 'Receita de Controle Especial (2 vias)'),
  ('IMICLOPRAZINA', 'C1', 'Receita de Controle Especial (2 vias)'),
  ('IMIPRAMINA', 'C1', 'Receita de Controle Especial (2 vias)'),
  ('IMIPRAMINOXIDO', 'C1', 'Receita de Controle Especial (2 vias)'),
  ('IPROCLORIZIDA', 'C1', 'Receita de Controle Especial (2 vias)'),
  ('ISOCARBOXAZIDA', 'C1', 'Receita de Controle Especial (2 vias)'),
  ('ISOFLURANO', 'C1', 'Receita de Controle Especial (2 vias)'),
  ('ISOPROPIL-CROTONIL-UREIA', 'C1', 'Receita de Controle Especial (2 vias)'),
  ('LAMOTRIGINA', 'C1', 'Receita de Controle Especial (2 vias)'),
  ('LEVODOPA', 'C1', 'Receita de Controle Especial (2 vias)'),
  ('LEVOMEPROMAZINA', 'C1', 'Receita de Controle Especial (2 vias)'),
  ('LINDANO', 'C1', 'Receita de Controle Especial (2 vias)'),
  ('LISURIDA', 'C1', 'Receita de Controle Especial (2 vias)'),
  ('LITIO', 'C1', 'Receita de Controle Especial (2 vias)'),
  ('LOPERAMIDA', 'C1', 'Receita de Controle Especial (2 vias)'),
  ('LOXAPINA', 'C1', 'Receita de Controle Especial (2 vias)'),
  ('MAPROTILINA', 'C1', 'Receita de Controle Especial (2 vias)'),
  ('MECLOFENOXATO', 'C1', 'Receita de Controle Especial (2 vias)'),
  ('MEFENOXALONA', 'C1', 'Receita de Controle Especial (2 vias)'),
  ('MEFEXAMIDA', 'C1', 'Receita de Controle Especial (2 vias)'),
  ('MEPAZINA', 'C1', 'Receita de Controle Especial (2 vias)'),
  ('MESORIDAZINA', 'C1', 'Receita de Controle Especial (2 vias)'),
  ('METILPENTINOL', 'C1', 'Receita de Controle Especial (2 vias)'),
  ('METISERGIDA', 'C1', 'Receita de Controle Especial (2 vias)'),
  ('METIXENO', 'C1', 'Receita de Controle Especial (2 vias)'),
  ('METOPROMAZINA', 'C1', 'Receita de Controle Especial (2 vias)'),
  ('METOXIFLURANO', 'C1', 'Receita de Controle Especial (2 vias)'),
  ('MIANSERINA', 'C1', 'Receita de Controle Especial (2 vias)'),
  ('MINACIPRAN', 'C1', 'Receita de Controle Especial (2 vias)'),
  ('MINAPRINA', 'C1', 'Receita de Controle Especial (2 vias)'),
  ('MIRTAZAPINA', 'C1', 'Receita de Controle Especial (2 vias)'),
  ('MISOPROSTOL', 'C1', 'Receita de Controle Especial (2 vias)'),
  ('MOCLOBEMIDA', 'C1', 'Receita de Controle Especial (2 vias)'),
  ('MOPERONA', 'C1', 'Receita de Controle Especial (2 vias)'),
  ('NALOXONA', 'C1', 'Receita de Controle Especial (2 vias)'),
  ('NALTREXONA', 'C1', 'Receita de Controle Especial (2 vias)'),
  ('NEFAZODONA', 'C1', 'Receita de Controle Especial (2 vias)'),
  ('NIALAMIDA', 'C1', 'Receita de Controle Especial (2 vias)'),
  ('NOMIFENSINA', 'C1', 'Receita de Controle Especial (2 vias)'),
  ('NORTRIPTILINA', 'C1', 'Receita de Controle Especial (2 vias)'),
  ('NOXPTILINA', 'C1', 'Receita de Controle Especial (2 vias)'),
  ('OLANZAPINA', 'C1', 'Receita de Controle Especial (2 vias)'),
  ('OPIPRAMOL', 'C1', 'Receita de Controle Especial (2 vias)'),
  ('ORLISTAT', 'C1', 'Receita de Controle Especial (2 vias)'),
  ('OXCARBAZEPINA', 'C1', 'Receita de Controle Especial (2 vias)'),
  ('OXIFENAMATO', 'C1', 'Receita de Controle Especial (2 vias)'),
  ('OXIPERTINA', 'C1', 'Receita de Controle Especial (2 vias)'),
  ('PAROXETINA', 'C1', 'Receita de Controle Especial (2 vias)'),
  ('PENFLURIDOL', 'C1', 'Receita de Controle Especial (2 vias)'),
  ('PERFENAZINA', 'C1', 'Receita de Controle Especial (2 vias)'),
  ('PERGOLIDA', 'C1', 'Receita de Controle Especial (2 vias)'),
  ('PERICIAZINA', 'C1', 'Receita de Controle Especial (2 vias)'),
  ('PROPERICIAZIDA', 'C1', 'Receita de Controle Especial (2 vias)'),
  ('PIMOZIDA', 'C1', 'Receita de Controle Especial (2 vias)'),
  ('PIPAMPERONA', 'C1', 'Receita de Controle Especial (2 vias)'),
  ('PIPOTIAZINA', 'C1', 'Receita de Controle Especial (2 vias)'),
  ('PRAMIPEXOL', 'C1', 'Receita de Controle Especial (2 vias)'),
  ('PRIMIDONA', 'C1', 'Receita de Controle Especial (2 vias)'),
  ('PROCLORPERAZINA', 'C1', 'Receita de Controle Especial (2 vias)'),
  ('PROMAZINA', 'C1', 'Receita de Controle Especial (2 vias)'),
  ('PROPANIDINA', 'C1', 'Receita de Controle Especial (2 vias)'),
  ('PROPIOMAZINA', 'C1', 'Receita de Controle Especial (2 vias)'),
  ('PROPOFOL', 'C1', 'Receita de Controle Especial (2 vias)'),
  ('PROTIPENDIL', 'C1', 'Receita de Controle Especial (2 vias)'),
  ('PROTRIPTILINA', 'C1', 'Receita de Controle Especial (2 vias)'),
  ('PROXIMETACAINA', 'C1', 'Receita de Controle Especial (2 vias)'),
  ('RISPERIDONA', 'C1', 'Receita de Controle Especial (2 vias)'),
  ('ROPINIROL', 'C1', 'Receita de Controle Especial (2 vias)'),
  ('SELEGILINA', 'C1', 'Receita de Controle Especial (2 vias)'),
  ('SERTRALINA', 'C1', 'Receita de Controle Especial (2 vias)'),
  ('SEVOLFURANO', 'C1', 'Receita de Controle Especial (2 vias)'),
  ('SIBUTRAMINA', 'C1', 'Receita de Controle Especial (2 vias)'),
  ('SILDENAFILA', 'C1', 'Receita de Controle Especial (2 vias)'),
  ('SULPIRIDA', 'C1', 'Receita de Controle Especial (2 vias)'),
  ('TACRINA', 'C1', 'Receita de Controle Especial (2 vias)'),
  ('TALCAPONA', 'C1', 'Receita de Controle Especial (2 vias)'),
  ('TETRACAINA', 'C1', 'Receita de Controle Especial (2 vias)'),
  ('TIANEPTINA', 'C1', 'Receita de Controle Especial (2 vias)'),
  ('TIAPRIDA', 'C1', 'Receita de Controle Especial (2 vias)'),
  ('TIOPROPERAZINA', 'C1', 'Receita de Controle Especial (2 vias)'),
  ('TIORIDAZINA', 'C1', 'Receita de Controle Especial (2 vias)'),
  ('TIOTIXENO', 'C1', 'Receita de Controle Especial (2 vias)'),
  ('TOPIRAMATO', 'C1', 'Receita de Controle Especial (2 vias)'),
  ('TRANILCIPROMINA', 'C1', 'Receita de Controle Especial (2 vias)'),
  ('TRAZODONA', 'C1', 'Receita de Controle Especial (2 vias)'),
  ('TRICLOFOS', 'C1', 'Receita de Controle Especial (2 vias)'),
  ('TRICLORETILENO', 'C1', 'Receita de Controle Especial (2 vias)'),
  ('TRIFLUOPERAZINA', 'C1', 'Receita de Controle Especial (2 vias)'),
  ('TRIFLUPERIDOL', 'C1', 'Receita de Controle Especial (2 vias)'),
  ('TRIMIPRAMINA', 'C1', 'Receita de Controle Especial (2 vias)'),
  ('VALPROATO SODICO', 'C1', 'Receita de Controle Especial (2 vias)'),
  ('VENLAFAXINA', 'C1', 'Receita de Controle Especial (2 vias)'),
  ('VERALIPRIDA', 'C1', 'Receita de Controle Especial (2 vias)'),
  ('VIGABATRINA', 'C1', 'Receita de Controle Especial (2 vias)'),
  ('ZIPRAZIDONA', 'C1', 'Receita de Controle Especial (2 vias)'),
  ('ZUCLOPENTIXOL', 'C1', 'Receita de Controle Especial (2 vias)'),
  ('ACITRETINA', 'C2', 'Notificação de Receita Especial (branca)'),
  ('ADAPALENO', 'C2', 'Notificação de Receita Especial (branca)'),
  ('ISOTRETINOINA', 'C2', 'Notificação de Receita Especial (branca)'),
  ('TRETINOINA', 'C2', 'Notificação de Receita Especial (branca)'),
  ('FTALIMIDOGLUTARIMIDA', 'C3', 'Notificação de Receita Especial (branca)'),
  ('TALIDOMIDA', 'C3', 'Notificação de Receita Especial (branca)'),
  ('DELAVIDINA', 'C4', 'Receituário DST/AIDS ou Receita de Controle Especial (2 vias)'),
  ('DIDANOSINA', 'C4', 'Receituário DST/AIDS ou Receita de Controle Especial (2 vias)'),
  ('DDI', 'C4', 'Receituário DST/AIDS ou Receita de Controle Especial (2 vias)'),
  ('EFAVIRENZ', 'C4', 'Receituário DST/AIDS ou Receita de Controle Especial (2 vias)'),
  ('ESTAVUDINA', 'C4', 'Receituário DST/AIDS ou Receita de Controle Especial (2 vias)'),
  ('INDINAVIR', 'C4', 'Receituário DST/AIDS ou Receita de Controle Especial (2 vias)'),
  ('LAMIVUDINA', 'C4', 'Receituário DST/AIDS ou Receita de Controle Especial (2 vias)'),
  ('NELFINAVIR', 'C4', 'Receituário DST/AIDS ou Receita de Controle Especial (2 vias)'),
  ('NEVIRAPINA', 'C4', 'Receituário DST/AIDS ou Receita de Controle Especial (2 vias)'),
  ('RITONAVIR', 'C4', 'Receituário DST/AIDS ou Receita de Controle Especial (2 vias)'),
  ('SAQUINAVIR', 'C4', 'Receituário DST/AIDS ou Receita de Controle Especial (2 vias)'),
  ('ZALCITABINA', 'C4', 'Receituário DST/AIDS ou Receita de Controle Especial (2 vias)'),
  ('DDC', 'C4', 'Receituário DST/AIDS ou Receita de Controle Especial (2 vias)'),
  ('ZIDOVUDINA', 'C4', 'Receituário DST/AIDS ou Receita de Controle Especial (2 vias)'),
  ('AZT', 'C4', 'Receituário DST/AIDS ou Receita de Controle Especial (2 vias)'),
  ('DIIDROEPIANDROSTERONA', 'C5', 'Receita de Controle Especial (2 vias)'),
  ('DHEA', 'C5', 'Receita de Controle Especial (2 vias)'),
  ('ESTANOZOLOL', 'C5', 'Receita de Controle Especial (2 vias)'),
  ('FLUOXIMESTERONA', 'C5', 'Receita de Controle Especial (2 vias)'),
  ('FLUOXIMETILTESTOSTERONA', 'C5', 'Receita de Controle Especial (2 vias)'),
  ('MESTEROLONA', 'C5', 'Receita de Controle Especial (2 vias)'),
  ('METANDRIOL', 'C5', 'Receita de Controle Especial (2 vias)'),
  ('METILTESTOSTERONA', 'C5', 'Receita de Controle Especial (2 vias)'),
  ('NANDROLONA', 'C5', 'Receita de Controle Especial (2 vias)'),
  ('OXIMETOLONA', 'C5', 'Receita de Controle Especial (2 vias)'),
  ('1-FENIL-2-PROPANONA', 'D1', 'Receita Médica sem Retenção'),
  ('4 - METILENDIOXIFENIL-2-PROPANONA', 'D1', 'Receita Médica sem Retenção'),
  ('ACIDO ANTRANILICO', 'D1', 'Receita Médica sem Retenção'),
  ('ACIDO FENILACETICO', 'D1', 'Receita Médica sem Retenção'),
  ('ACIDO LISERGICO', 'D1', 'Receita Médica sem Retenção'),
  ('ACIDO N-ACETILANTRANILICO', 'D1', 'Receita Médica sem Retenção'),
  ('EFEDRINA', 'D1', 'Receita Médica sem Retenção'),
  ('ERGOMETRINA', 'D1', 'Receita Médica sem Retenção'),
  ('ERGOTAMINA', 'D1', 'Receita Médica sem Retenção'),
  ('ISOSAFROL', 'D1', 'Receita Médica sem Retenção'),
  ('PIPERIDINA', 'D1', 'Receita Médica sem Retenção'),
  ('PIPERONAL', 'D1', 'Receita Médica sem Retenção'),
  ('PSEUDOEFEDRINA', 'D1', 'Receita Médica sem Retenção'),
  ('SAFROL', 'D1', 'Receita Médica sem Retenção'),
  ('ACETONA', 'D2', 'Controle do Ministério da Justiça (não sujeito a receita)'),
  ('ACIDO CLORIDRICO', 'D2', 'Controle do Ministério da Justiça (não sujeito a receita)'),
  ('ACIDO SULFURICO', 'D2', 'Controle do Ministério da Justiça (não sujeito a receita)'),
  ('ANIDRIDO ACETICO', 'D2', 'Controle do Ministério da Justiça (não sujeito a receita)'),
  ('CLORETO DE METILENO', 'D2', 'Controle do Ministério da Justiça (não sujeito a receita)'),
  ('CLOROFORMIO', 'D2', 'Controle do Ministério da Justiça (não sujeito a receita)'),
  ('ETER ETILICO', 'D2', 'Controle do Ministério da Justiça (não sujeito a receita)'),
  ('METIL ETIL CETONA', 'D2', 'Controle do Ministério da Justiça (não sujeito a receita)'),
  ('PERMANGANATO DE POTASSIO', 'D2', 'Controle do Ministério da Justiça (não sujeito a receita)'),
  ('SULFATO DE SODIO', 'D2', 'Controle do Ministério da Justiça (não sujeito a receita)'),
  ('TOLUENO', 'D2', 'Controle do Ministério da Justiça (não sujeito a receita)'),
  ('CANNABIS SATIVUM', 'E', 'Proibida prescrição/manipulação (planta de origem controlada)'),
  ('CLAVICEPS PASPALI', 'E', 'Proibida prescrição/manipulação (planta de origem controlada)'),
  ('DATURA SUAVEOLANS', 'E', 'Proibida prescrição/manipulação (planta de origem controlada)'),
  ('ERYTROXYLUM COCA', 'E', 'Proibida prescrição/manipulação (planta de origem controlada)'),
  ('LOPHOPHORA WILLIAMSII', 'E', 'Proibida prescrição/manipulação (planta de origem controlada)'),
  ('CACTO PEYOTE', 'E', 'Proibida prescrição/manipulação (planta de origem controlada)'),
  ('PRESTONIA AMAZONICA', 'E', 'Proibida prescrição/manipulação (planta de origem controlada)'),
  ('HAEMADICTYON AMAZONICUM', 'E', 'Proibida prescrição/manipulação (planta de origem controlada)'),
  ('3-METILFENTANILA', 'F1', 'Uso proscrito no Brasil - não sujeito a prescrição'),
  ('3-METILTIOFENTANILA', 'F1', 'Uso proscrito no Brasil - não sujeito a prescrição'),
  ('ACETIL-ALFA-METILFENTANILA', 'F1', 'Uso proscrito no Brasil - não sujeito a prescrição'),
  ('ALFA-METILFENTANILA', 'F1', 'Uso proscrito no Brasil - não sujeito a prescrição'),
  ('ALFAMETILTIOFENTANIL', 'F1', 'Uso proscrito no Brasil - não sujeito a prescrição'),
  ('BETA-HIDROXI-3-METILFENTANILA', 'F1', 'Uso proscrito no Brasil - não sujeito a prescrição'),
  ('BETA-HIDROXIFENTANILA', 'F1', 'Uso proscrito no Brasil - não sujeito a prescrição'),
  ('COCAINA', 'F1', 'Uso proscrito no Brasil - não sujeito a prescrição'),
  ('DESOMORFINA', 'F1', 'Uso proscrito no Brasil - não sujeito a prescrição'),
  ('DIIDRODEOXIMORFINA', 'F1', 'Uso proscrito no Brasil - não sujeito a prescrição'),
  ('ECGONINA', 'F1', 'Uso proscrito no Brasil - não sujeito a prescrição'),
  ('HEROINA', 'F1', 'Uso proscrito no Brasil - não sujeito a prescrição'),
  ('DIACETILMORFINA', 'F1', 'Uso proscrito no Brasil - não sujeito a prescrição'),
  ('MPPP', 'F1', 'Uso proscrito no Brasil - não sujeito a prescrição'),
  ('PARA-FLUOROFENTANILA', 'F1', 'Uso proscrito no Brasil - não sujeito a prescrição'),
  ('PEPAP', 'F1', 'Uso proscrito no Brasil - não sujeito a prescrição'),
  ('TIOFENTANILA', 'F1', 'Uso proscrito no Brasil - não sujeito a prescrição'),
  ('4-METILAMINOREX', 'F2', 'Uso proscrito no Brasil - não sujeito a prescrição'),
  ('BENZOFETAMINA', 'F2', 'Uso proscrito no Brasil - não sujeito a prescrição'),
  ('CATINONA', 'F2', 'Uso proscrito no Brasil - não sujeito a prescrição'),
  ('CLORETO DE ETILA', 'F2', 'Uso proscrito no Brasil - não sujeito a prescrição'),
  ('DET', 'F2', 'Uso proscrito no Brasil - não sujeito a prescrição'),
  ('LISERGIDA', 'F2', 'Uso proscrito no Brasil - não sujeito a prescrição'),
  ('LSD', 'F2', 'Uso proscrito no Brasil - não sujeito a prescrição'),
  ('DMA', 'F2', 'Uso proscrito no Brasil - não sujeito a prescrição'),
  ('DMHP', 'F2', 'Uso proscrito no Brasil - não sujeito a prescrição'),
  ('DMT', 'F2', 'Uso proscrito no Brasil - não sujeito a prescrição'),
  ('DOB', 'F2', 'Uso proscrito no Brasil - não sujeito a prescrição'),
  ('DOET', 'F2', 'Uso proscrito no Brasil - não sujeito a prescrição'),
  ('ETICICLIDINA', 'F2', 'Uso proscrito no Brasil - não sujeito a prescrição'),
  ('PCE', 'F2', 'Uso proscrito no Brasil - não sujeito a prescrição'),
  ('ETRIPTAMINA', 'F2', 'Uso proscrito no Brasil - não sujeito a prescrição'),
  ('MDA', 'F2', 'Uso proscrito no Brasil - não sujeito a prescrição'),
  ('MDMA', 'F2', 'Uso proscrito no Brasil - não sujeito a prescrição'),
  ('MECLOQUALONA', 'F2', 'Uso proscrito no Brasil - não sujeito a prescrição'),
  ('MESCALINA', 'F2', 'Uso proscrito no Brasil - não sujeito a prescrição'),
  ('METAQUALONA', 'F2', 'Uso proscrito no Brasil - não sujeito a prescrição'),
  ('METICATINONA', 'F2', 'Uso proscrito no Brasil - não sujeito a prescrição'),
  ('MMDA', 'F2', 'Uso proscrito no Brasil - não sujeito a prescrição'),
  ('PARAHEXILA', 'F2', 'Uso proscrito no Brasil - não sujeito a prescrição'),
  ('PMA', 'F2', 'Uso proscrito no Brasil - não sujeito a prescrição'),
  ('PSILOCIBINA', 'F2', 'Uso proscrito no Brasil - não sujeito a prescrição'),
  ('PSILOCINA', 'F2', 'Uso proscrito no Brasil - não sujeito a prescrição'),
  ('ROLICICLIDINA', 'F2', 'Uso proscrito no Brasil - não sujeito a prescrição'),
  ('STP', 'F2', 'Uso proscrito no Brasil - não sujeito a prescrição'),
  ('DOM', 'F2', 'Uso proscrito no Brasil - não sujeito a prescrição'),
  ('TENOCICLIDINA', 'F2', 'Uso proscrito no Brasil - não sujeito a prescrição'),
  ('THC', 'F2', 'Uso proscrito no Brasil - não sujeito a prescrição'),
  ('TETRAIDROCANABINOL', 'F2', 'Uso proscrito no Brasil - não sujeito a prescrição'),
  ('TMA', 'F2', 'Uso proscrito no Brasil - não sujeito a prescrição'),
  ('ZIPEPROL', 'F2', 'Uso proscrito no Brasil - não sujeito a prescrição'),
  ('ESTRICNINA', 'F3', 'Uso proscrito no Brasil - não sujeito a prescrição'),
  ('ETRETINATO', 'F3', 'Uso proscrito no Brasil - não sujeito a prescrição')
  ) AS v(nome, lista, tipo_receita)
    ON (
      public.normaliza_substancia(s.grupo_busca)   ~ ('(^|[^A-Z0-9])' || v.nome || '($|[^A-Z0-9])')
      OR public.normaliza_substancia(s.nome_dcb)      ~ ('(^|[^A-Z0-9])' || v.nome || '($|[^A-Z0-9])')
      OR public.normaliza_substancia(s.nome_exibicao) ~ ('(^|[^A-Z0-9])' || v.nome || '($|[^A-Z0-9])')
    )
),
melhores AS (
  SELECT DISTINCT ON (id_substancia) id_substancia, lista, tipo_receita
  FROM candidatos
  ORDER BY id_substancia, especificidade DESC
)
UPDATE public.substancias s
SET
  lista_portaria344 = m.lista,
  tipo_receita = m.tipo_receita
FROM melhores m
WHERE m.id_substancia = s.id_substancia;
